Remove xercesImpl dependency
It was breaking tomcat with:

java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

I did not get to the bottom of this; some googling suggesting xercerImpl
should be used side by side with xml-apis, but
spring-security-saml2-core's POM excludes xml-apis. Since the federated
login works fine without xercesImpl, I opted to remove it instead.